
MENU_LoadMain = 1
MENU_LoadDll = 2
MENU_FasFileTest = 3
MENU_Settings = 4
MENU_About = 5
 
ID_ICON_MAIN = 101
 
ID_DLG_SETTINGS = 601
dlg_settings_codepage_info = 602
dlg_settings_codepage_select = 603
dlg_settings_delete_old_labels = 604
dlg_settings_import_labels = 605
dlg_settings_delete_old_comments = 606
dlg_settings_import_sources = 607
dlg_settings_append_labels = 608
dlg_settings_remove_spaces = 609
dlg_settings_spaces_as_tabs = 610
dlg_settings_tabsize_info = 611
dlg_settings_tabsize1 = 612
dlg_settings_tabsize2 = 613
dlg_settings_tabsize3 = 614
dlg_settings_tabsize4 = 615
dlg_settings_tabsize5 = 616
dlg_settings_tabsize_def = 617
dlg_settings_flag_MANUAL_labels = 621
dlg_settings_flag_MANUAL_comments = 622
dlg_settings_flags_info = 623
dlg_settings_OFN_force = 624
dlg_settings_ok = 650
dlg_settings_cancel = 651

ID_DLG_DLL = 701
dlg_dll_list = 710
dlg_dll_cancel = 711
dlg_dll_load = 712

ID_DLG_FASFILETEST = 750
dlg_FasFileTest_list = 751
dlg_FasFileTest_close = 752

ID_DLG_ABOUT = 801
dlg_about_version = 802
dlg_about_desc1 = 803
dlg_about_author = 804
dlg_about_author_url = 805
dlg_about_sources = 806
dlg_about_sources_url = 807
dlg_about_forum = 808
dlg_about_forum_url = 809
dlg_about_desc2 = 810
dlg_about_help_fas = 811
dlg_about_langcode = 812
dlg_about_langcode_data = 813
dlg_about_lang_author = 814
dlg_about_lang_author_data = 815
dlg_about_lang_version = 816
dlg_about_lang_version_data = 817
dlg_about_lang_status = 820
dlg_about_close = 830

